// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLq2tfpH6y1ht8ZGM6AOMIpR5LXuiVxdg',
    appId: '1:828910928116:web:37fcfbc10a61f350dd9ea1',
    messagingSenderId: '828910928116',
    projectId: 'msg-in',
    authDomain: 'msg-in.firebaseapp.com',
    storageBucket: 'msg-in.appspot.com',
    measurementId: 'G-G6QZPRZQGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7hH0mG5Z5Gnj575tquxEk7vosvewc908',
    appId: '1:828910928116:android:7d6432330613689edd9ea1',
    messagingSenderId: '828910928116',
    projectId: 'msg-in',
    storageBucket: 'msg-in.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLq2tfpH6y1ht8ZGM6AOMIpR5LXuiVxdg',
    appId: '1:828910928116:web:dbcbd6b079e48c7edd9ea1',
    messagingSenderId: '828910928116',
    projectId: 'msg-in',
    authDomain: 'msg-in.firebaseapp.com',
    storageBucket: 'msg-in.appspot.com',
    measurementId: 'G-NTG0G7V395',
  );
}
